name: clover
description: 'Clover is an open source framework for building MVVM applications with Flutter.'
version: 4.0.0
repository: https://github.com/yanshouwang/clover
issue_tracker: https://github.com/yanshouwang/clover/issues
topics:
  - clover
  - mvvm

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
