name: clover
description: "Clover is an open source framework for building MVVM applications with Flutter."
version: 3.0.0
homepage: https://github.com/yanshouwang/clover
repository: https://github.com/yanshouwang/clover
issue_tracker: https://github.com/yanshouwang/clover/issues
topics:
  - clover
  - mvvm
funding:
  - https://paypal.me/yanshouwang5112
  - https://afdian.net/a/yanshouwang

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10

flutter: